namespace Mavi.Application.Modules.Intelligence;

public sealed record TrackSearchPage(
    IReadOnlyList<TrackSearchRow> Items,
    string? NextCursor);

public sealed record TrackSearchRow(
    Guid Id,
    Guid ProcessingRunId,
    Guid VideoAssetId,
    Guid CameraId,
    string CameraCode,
    string CameraName,
    string ObjectClass,
    DateTimeOffset StartTimestampUtc,
    DateTimeOffset EndTimestampUtc,
    long StartOffsetMs,
    long EndOffsetMs,
    long DurationMs,
    int DetectionCount,
    double MeanConfidence,
    double MaxConfidence,
    string ReviewStatus,
    Guid? ThumbnailArtifactId);

public sealed record TrackDetailRow(
    Guid Id,
    Guid ProcessingRunId,
    Guid VideoAssetId,
    Guid CameraId,
    string CameraCode,
    string CameraName,
    string ObjectClass,
    int LocalTrackNumber,
    long StartOffsetMs,
    long EndOffsetMs,
    DateTimeOffset StartTimestampUtc,
    DateTimeOffset EndTimestampUtc,
    long DurationMs,
    int DetectionCount,
    double MeanConfidence,
    double MaxConfidence,
    string ReviewStatus,
    string PipelineVersion,
    string? DetectorName,
    string? DetectorVersion,
    string? TrackerName,
    string? TrackerVersion,
    DateTimeOffset CompletedAtUtc,
    DateTimeOffset RecordingStartUtc,
    DateTimeOffset RecordingEndUtc,
    long VideoDurationMs,
    int Width,
    int Height,
    int FrameRateNumerator,
    int FrameRateDenominator,
    Guid? RepresentativeObservationId,
    long? RepresentativeSourceFrameNumber,
    long? RepresentativeVideoOffsetMs,
    DateTimeOffset? RepresentativeTimestampUtc,
    double? RepresentativeConfidence,
    double? RepresentativeQualityScore,
    float? BoundingBoxX,
    float? BoundingBoxY,
    float? BoundingBoxWidth,
    float? BoundingBoxHeight,
    Guid? ThumbnailArtifactId,
    Guid? TrajectoryArtifactId);
