namespace Mavi.Application.Modules.Intelligence;

/// <summary>
/// Server-held configuration of the Track search surface.
/// </summary>
/// <remarks>
/// <para>
/// <see cref="CursorSigningKey"/> authenticates analytic (v3) cursors, which carry
/// server-derived state — the pinned scene identity and the coverage snapshot — that
/// the server must be able to trust on the way back in (plan §S, ADR-011 decision 6).
/// It is a base64 encoding of exactly 32 random bytes, generated by setup for the
/// installation and written to the machine configuration file beside the connection
/// string. It is never returned by an API, never logged and never committed.
/// </para>
/// <para>
/// Rotating or losing the key deliberately invalidates every outstanding v3 cursor and
/// nothing else: ordinary v2 cursors carry no trusted server state and are unsigned.
/// </para>
/// <para>
/// <see cref="AllowEphemeralCursorSigningKey"/> lets a host without a configured key
/// start with a random per-process key instead. The API host accepts that only in the
/// Development and Testing environments; a Production host with no key refuses to
/// start, because silently minting one would make every restart look like a key
/// rotation to operators who never asked for one.
/// </para>
/// </remarks>
public sealed class TrackSearchOptions
{
    public const string SectionName = "TrackSearch";

    public string? CursorSigningKey { get; init; }

    public bool AllowEphemeralCursorSigningKey { get; init; }
}
