// <auto-generated />
using System;
using Mavi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mavi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaviDbContext))]
    [Migration("20260909022831_AddSourceVideoShaUniqueness")]
    partial class AddSourceVideoShaUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mavi.Domain.Cameras.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_code");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IdentityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("identity_status");

                    b.Property<Guid?>("RepresentativeArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_artifact_id");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DisplayCode")
                        .IsUnique();

                    b.HasIndex("RepresentativeArtifactId");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("BoundingBoxHeight")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_height");

                    b.Property<float>("BoundingBoxWidth")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_width");

                    b.Property<float>("BoundingBoxX")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_x");

                    b.Property<float>("BoundingBoxY")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_y");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ObservationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("observation_type");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<long>("SourceFrameNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("source_frame_number");

                    b.Property<Guid?>("ThumbnailArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_artifact_id");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<long>("VideoOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("video_offset_ms");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailArtifactId");

                    b.HasIndex("TrackId");

                    b.ToTable("observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_observations_box", "bounding_box_x >= 0 AND bounding_box_y >= 0 AND bounding_box_width >= 0 AND bounding_box_height >= 0 AND bounding_box_x + bounding_box_width <= 1 AND bounding_box_y + bounding_box_height <= 1");

                            t.HasCheckConstraint("ck_observations_scores", "confidence >= 0 AND confidence <= 1 AND quality_score >= 0 AND quality_score <= 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DetectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("detection_count");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<long>("EndOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("end_offset_ms");

                    b.Property<DateTimeOffset>("EndTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_timestamp_utc");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("LocalTrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("local_track_number");

                    b.Property<double>("MaxConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("max_confidence");

                    b.Property<double>("MeanConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("mean_confidence");

                    b.Property<string>("ObjectClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("object_class");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_run_id");

                    b.Property<Guid?>("RepresentativeObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_observation_id");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_status");

                    b.Property<long>("StartOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("start_offset_ms");

                    b.Property<DateTimeOffset>("StartTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_timestamp_utc");

                    b.Property<Guid?>("TrajectoryArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("trajectory_artifact_id");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("RepresentativeObservationId");

                    b.HasIndex("TrajectoryArtifactId");

                    b.HasIndex("ObjectClass", "StartTimestampUtc");

                    b.HasIndex("ProcessingRunId", "LocalTrackNumber")
                        .IsUnique();

                    b.HasIndex("VideoAssetId", "StartTimestampUtc");

                    b.ToTable("tracks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tracks_confidence", "mean_confidence >= 0 AND mean_confidence <= 1 AND max_confidence >= 0 AND max_confidence <= 1");

                            t.HasCheckConstraint("ck_tracks_detections", "detection_count > 0");

                            t.HasCheckConstraint("ck_tracks_duration", "duration_ms = end_offset_ms - start_offset_ms");

                            t.HasCheckConstraint("ck_tracks_offsets", "start_offset_ms >= 0 AND end_offset_ms >= start_offset_ms");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.VisualAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attribute_type");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_version");

                    b.Property<Guid?>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId");

                    b.HasIndex("TrackId");

                    b.ToTable("visual_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_visual_attributes_confidence", "confidence >= 0 AND confidence <= 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Media.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("artifact_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ux_artifacts_source_video_sha256")
                        .HasFilter("artifact_type = 'SourceVideo'");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_artifacts_size", "size_bytes >= 0");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Media.VideoAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("codec");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int>("FrameRateDenominator")
                        .HasColumnType("integer")
                        .HasColumnName("frame_rate_denominator");

                    b.Property<int>("FrameRateNumerator")
                        .HasColumnType("integer")
                        .HasColumnName("frame_rate_numerator");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_status");

                    b.Property<DateTimeOffset>("RecordingEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recording_end_utc");

                    b.Property<DateTimeOffset>("RecordingStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recording_start_utc");

                    b.Property<Guid>("SourceArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_artifact_id");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_reference");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<double>("TimestampConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("timestamp_confidence");

                    b.Property<string>("TimestampSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("timestamp_source");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAtUtc");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("SourceArtifactId");

                    b.HasIndex("CameraId", "RecordingStartUtc");

                    b.ToTable("video_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_video_assets_dimensions", "width > 0 AND height > 0");

                            t.HasCheckConstraint("ck_video_assets_duration", "duration_ms > 0");

                            t.HasCheckConstraint("ck_video_assets_frame_rate", "frame_rate_numerator > 0 AND frame_rate_denominator > 0");

                            t.HasCheckConstraint("ck_video_assets_recording_end", "recording_end_utc = recording_start_utc + duration_ms * INTERVAL '1 millisecond'");

                            t.HasCheckConstraint("ck_video_assets_timestamp_confidence", "timestamp_confidence >= 0 AND timestamp_confidence <= 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Processing.ProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<string>("DetectorName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("detector_name");

                    b.Property<string>("DetectorVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("detector_version");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_details");

                    b.Property<long>("FramesProcessed")
                        .HasColumnType("bigint")
                        .HasColumnName("frames_processed");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pipeline_version");

                    b.Property<long?>("ProcessingDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_duration_ms");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TrackerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tracker_name");

                    b.Property<string>("TrackerVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tracker_version");

                    b.Property<int>("TracksCreated")
                        .HasColumnType("integer")
                        .HasColumnName("tracks_created");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VideoAssetId");

                    b.ToTable("processing_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_processing_runs_frames", "frames_processed >= 0");

                            t.HasCheckConstraint("ck_processing_runs_tracks", "tracks_created >= 0");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Processing.VisionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("failure_details");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("Pipeline")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pipeline");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_run_id");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("progress_percent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRunId")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAtUtc");

                    b.ToTable("vision_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_vision_jobs_attempts", "attempt_count >= 0 AND attempt_count <= 3");

                            t.HasCheckConstraint("ck_vision_jobs_progress", "progress_percent >= 0 AND progress_percent <= 100");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Entity", b =>
                {
                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("RepresentativeArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Observation", b =>
                {
                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Track", b =>
                {
                    b.HasOne("Mavi.Domain.Intelligence.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Processing.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Intelligence.Observation", null)
                        .WithMany()
                        .HasForeignKey("RepresentativeObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("TrajectoryArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Media.VideoAsset", null)
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.VisualAttribute", b =>
                {
                    b.HasOne("Mavi.Domain.Intelligence.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Media.VideoAsset", b =>
                {
                    b.HasOne("Mavi.Domain.Cameras.Camera", null)
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("SourceArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Processing.ProcessingRun", b =>
                {
                    b.HasOne("Mavi.Domain.Media.VideoAsset", null)
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Processing.VisionJob", b =>
                {
                    b.HasOne("Mavi.Domain.Processing.ProcessingRun", null)
                        .WithOne()
                        .HasForeignKey("Mavi.Domain.Processing.VisionJob", "ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
