// <auto-generated />
using System;
using System.Collections.Generic;
using Mavi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mavi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaviDbContext))]
    partial class MaviDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("processing_visibility_sequence");

            modelBuilder.Entity("Mavi.Domain.Cameras.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("location_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_code");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IdentityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("identity_status");

                    b.Property<Guid?>("RepresentativeArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_artifact_id");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DisplayCode")
                        .IsUnique();

                    b.HasIndex("RepresentativeArtifactId");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("BoundingBoxHeight")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_height");

                    b.Property<float>("BoundingBoxWidth")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_width");

                    b.Property<float>("BoundingBoxX")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_x");

                    b.Property<float>("BoundingBoxY")
                        .HasColumnType("real")
                        .HasColumnName("bounding_box_y");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ObservationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("observation_type");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<long>("SourceFrameNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("source_frame_number");

                    b.Property<Guid?>("ThumbnailArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_artifact_id");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<long>("VideoOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("video_offset_ms");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailArtifactId");

                    b.HasIndex("TrackId");

                    b.ToTable("observations", null, t =>
                        {
                            t.HasCheckConstraint("ck_observations_box", "bounding_box_x >= 0 AND bounding_box_y >= 0 AND bounding_box_width >= 0 AND bounding_box_height >= 0 AND bounding_box_x + bounding_box_width <= 1 AND bounding_box_y + bounding_box_height <= 1");

                            t.HasCheckConstraint("ck_observations_scores", "confidence >= 0 AND confidence <= 1 AND quality_score >= 0 AND quality_score <= 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DetectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("detection_count");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<long>("EndOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("end_offset_ms");

                    b.Property<DateTimeOffset>("EndTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_timestamp_utc");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int>("LocalTrackNumber")
                        .HasColumnType("integer")
                        .HasColumnName("local_track_number");

                    b.Property<double>("MaxConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("max_confidence");

                    b.Property<double>("MeanConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("mean_confidence");

                    b.Property<string>("ObjectClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("object_class");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_run_id");

                    b.Property<Guid?>("RepresentativeObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_observation_id");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("review_status");

                    b.Property<long>("StartOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("start_offset_ms");

                    b.Property<DateTimeOffset>("StartTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_timestamp_utc");

                    b.Property<Guid?>("TrajectoryArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("trajectory_artifact_id");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("RepresentativeObservationId");

                    b.HasIndex("TrajectoryArtifactId");

                    b.HasIndex("ObjectClass", "StartTimestampUtc");

                    b.HasIndex("ProcessingRunId", "LocalTrackNumber")
                        .IsUnique();

                    b.HasIndex("VideoAssetId", "StartTimestampUtc");

                    b.ToTable("tracks", null, t =>
                        {
                            t.HasCheckConstraint("ck_tracks_confidence", "mean_confidence >= 0 AND mean_confidence <= 1 AND max_confidence >= 0 AND max_confidence <= 1");

                            t.HasCheckConstraint("ck_tracks_detections", "detection_count > 0");

                            t.HasCheckConstraint("ck_tracks_duration", "duration_ms = end_offset_ms - start_offset_ms");

                            t.HasCheckConstraint("ck_tracks_offsets", "start_offset_ms >= 0 AND end_offset_ms >= start_offset_ms");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.VisualAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attribute_type");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_version");

                    b.Property<Guid?>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId");

                    b.HasIndex("TrackId");

                    b.ToTable("visual_attributes", null, t =>
                        {
                            t.HasCheckConstraint("ck_visual_attributes_confidence", "confidence >= 0 AND confidence <= 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Media.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("artifact_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique()
                        .HasDatabaseName("ux_artifacts_source_video_sha256")
                        .HasFilter("artifact_type = 'SourceVideo'");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_artifacts_size", "size_bytes >= 0");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Media.VideoAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("codec");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int>("FrameRateDenominator")
                        .HasColumnType("integer")
                        .HasColumnName("frame_rate_denominator");

                    b.Property<int>("FrameRateNumerator")
                        .HasColumnType("integer")
                        .HasColumnName("frame_rate_numerator");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at_utc");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_status");

                    b.Property<DateTimeOffset>("RecordingEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recording_end_utc");

                    b.Property<DateTimeOffset>("RecordingStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recording_start_utc");

                    b.Property<string>("RecordingTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("recording_time_zone_id");

                    b.Property<int>("RecordingUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("recording_utc_offset_minutes");

                    b.Property<Guid>("SourceArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_artifact_id");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_reference");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<double>("TimestampConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("timestamp_confidence");

                    b.Property<string>("TimestampSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("timestamp_source");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAtUtc");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("SourceArtifactId");

                    b.HasIndex("CameraId", "RecordingStartUtc");

                    b.ToTable("video_assets", null, t =>
                        {
                            t.HasCheckConstraint("ck_video_assets_dimensions", "width > 0 AND height > 0");

                            t.HasCheckConstraint("ck_video_assets_duration", "duration_ms > 0");

                            t.HasCheckConstraint("ck_video_assets_frame_rate", "frame_rate_numerator > 0 AND frame_rate_denominator > 0");

                            t.HasCheckConstraint("ck_video_assets_recording_end", "recording_end_utc = recording_start_utc + duration_ms * INTERVAL '1 millisecond'");

                            t.HasCheckConstraint("ck_video_assets_recording_utc_offset", "recording_utc_offset_minutes BETWEEN -840 AND 840");

                            t.HasCheckConstraint("ck_video_assets_timestamp_confidence", "timestamp_confidence >= 0 AND timestamp_confidence <= 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Processing.ProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<string>("DetectorName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("detector_name");

                    b.Property<string>("DetectorVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("detector_version");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_details");

                    b.Property<long>("FramesProcessed")
                        .HasColumnType("bigint")
                        .HasColumnName("frames_processed");

                    b.Property<string>("PipelineVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pipeline_version");

                    b.Property<long?>("ProcessingDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_duration_ms");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<string>("RuntimeProvenanceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("runtime_provenance_json");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TrackerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tracker_name");

                    b.Property<string>("TrackerVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tracker_version");

                    b.Property<int>("TracksCreated")
                        .HasColumnType("integer")
                        .HasColumnName("tracks_created");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.Property<long?>("VisibilitySequence")
                        .HasColumnType("bigint")
                        .HasColumnName("visibility_sequence");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VideoAssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_processing_runs_active_video")
                        .HasFilter("status IN ('Queued', 'Running')");

                    b.HasIndex("VisibilitySequence")
                        .IsUnique()
                        .HasDatabaseName("ux_processing_runs_visibility_sequence")
                        .HasFilter("visibility_sequence IS NOT NULL");

                    b.HasIndex("VideoAssetId", "VisibilitySequence")
                        .HasDatabaseName("ix_processing_runs_video_visibility")
                        .HasFilter("status = 'Completed' AND visibility_sequence IS NOT NULL");

                    b.ToTable("processing_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_processing_runs_frames", "frames_processed >= 0");

                            t.HasCheckConstraint("ck_processing_runs_tracks", "tracks_created >= 0");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Processing.VisionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CompletionDigest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("completion_digest");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("failure_details");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<byte[]>("LeaseTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("lease_token_hash");

                    b.Property<string>("Pipeline")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pipeline");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_run_id");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("progress_percent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_vision_jobs_expired_lease")
                        .HasFilter("status = 'Leased'");

                    b.HasIndex("ProcessingRunId")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAtUtc");

                    b.ToTable("vision_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_vision_jobs_attempts", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_vision_jobs_completion_digest", "completion_digest IS NULL OR completion_digest ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_vision_jobs_lease_token_hash", "lease_token_hash IS NULL OR octet_length(lease_token_hash) = 32");

                            t.HasCheckConstraint("ck_vision_jobs_progress", "progress_percent >= 0 AND progress_percent <= 100");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Scene.SceneConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_revision_id");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRevisionId")
                        .HasDatabaseName("ix_scene_configurations_active_revision");

                    b.HasIndex("CameraId")
                        .IsUnique()
                        .HasDatabaseName("ux_scene_configurations_camera");

                    b.ToTable("scene_configurations", (string)null);
                });

            modelBuilder.Entity("Mavi.Domain.Scene.SceneConfigurationRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<long?>("ReferenceFrameOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_frame_offset_ms");

                    b.Property<Guid?>("ReferenceFrameVideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_frame_video_asset_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<Guid>("SceneConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_configuration_id");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceFrameVideoAssetId");

                    b.HasIndex("Id", "SceneConfigurationId")
                        .IsUnique()
                        .HasDatabaseName("ux_scene_revisions_id_configuration");

                    b.HasIndex("SceneConfigurationId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_scene_revisions_configuration_number");

                    b.ToTable("scene_configuration_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_scene_revisions_number", "revision_number >= 1");

                            t.HasCheckConstraint("ck_scene_revisions_reference_frame", "(reference_frame_video_asset_id IS NULL AND reference_frame_offset_ms IS NULL) OR (reference_frame_video_asset_id IS NOT NULL AND reference_frame_offset_ms IS NOT NULL AND reference_frame_offset_ms >= 0)");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Scene.SceneZone", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int?>("LoiteringThresholdSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("loitering_threshold_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Vertices")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vertices");

                    b.HasKey("RevisionId", "ZoneId");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_scene_zones_zone");

                    b.ToTable("scene_zones", null, t =>
                        {
                            t.HasCheckConstraint("ck_scene_zones_loitering_threshold", "loitering_threshold_seconds IS NULL OR (loitering_threshold_seconds > 0 AND loitering_threshold_seconds <= 86400)");

                            t.HasCheckConstraint("ck_scene_zones_vertex_count", "jsonb_array_length(vertices) BETWEEN 3 AND 64");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Scene.TripLine", b =>
                {
                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<string>("AToBLabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("a_to_b_label");

                    b.Property<string>("BToALabel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("b_to_a_label");

                    b.Property<bool>("Directed")
                        .HasColumnType("boolean")
                        .HasColumnName("directed");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "A", "Mavi.Domain.Scene.TripLine.A#NormalizedPoint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("ax");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("ay");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "B", "Mavi.Domain.Scene.TripLine.B#NormalizedPoint", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("bx");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("by");
                        });

                    b.HasKey("RevisionId", "LineId");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_trip_lines_line");

                    b.ToTable("trip_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_trip_lines_range", "ax BETWEEN 0 AND 1 AND ay BETWEEN 0 AND 1 AND bx BETWEEN 0 AND 1 AND by BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.SceneAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("algorithm_version");

                    b.Property<int>("AnalysedTrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("analysed_track_count");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<byte[]>("ClaimTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("claim_token_hash");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("failure_details");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("ParametersSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parameters_sha256");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_run_id");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at_utc");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("revision_id");

                    b.Property<string>("SourceCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_commit");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("UnavailableTrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("unavailable_track_count");

                    b.Property<long?>("VisibilitySequence")
                        .HasColumnType("bigint")
                        .HasColumnName("visibility_sequence");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingRunId")
                        .HasDatabaseName("ix_scene_analyses_run");

                    b.HasIndex("RevisionId");

                    b.HasIndex("VisibilitySequence")
                        .IsUnique()
                        .HasDatabaseName("ux_scene_analyses_visibility_sequence")
                        .HasFilter("visibility_sequence IS NOT NULL");

                    b.HasIndex("Status", "QueuedAtUtc")
                        .HasDatabaseName("ix_scene_analyses_pending")
                        .HasFilter("status IN ('Queued', 'Running')");

                    b.HasIndex("ProcessingRunId", "RevisionId", "AlgorithmVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_scene_analyses_identity");

                    b.ToTable("scene_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_scene_analyses_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_scene_analyses_claim_token_hash", "claim_token_hash IS NULL OR octet_length(claim_token_hash) = 32");

                            t.HasCheckConstraint("ck_scene_analyses_parameters_sha256", "parameters_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_scene_analyses_status", "status IN ('Queued', 'Running', 'Completed', 'Failed', 'Superseded')");

                            t.HasCheckConstraint("ck_scene_analyses_track_counts", "analysed_track_count >= 0 AND unavailable_track_count >= 0");

                            t.HasCheckConstraint("ck_scene_analyses_visibility_sequence", "visibility_sequence IS NULL OR visibility_sequence > 0");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackAnalysisOutcome", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<int>("GapCount")
                        .HasColumnType("integer")
                        .HasColumnName("gap_count");

                    b.Property<long>("GapTotalMs")
                        .HasColumnType("bigint")
                        .HasColumnName("gap_total_ms");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason");

                    b.Property<string>("ReferencePoint")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_point");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("sample_count");

                    b.HasKey("AnalysisId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("track_analysis_outcomes", null, t =>
                        {
                            t.HasCheckConstraint("ck_track_analysis_outcomes_counts", "sample_count >= 0 AND gap_count >= 0 AND gap_total_ms >= 0");

                            t.HasCheckConstraint("ck_track_analysis_outcomes_outcome", "outcome IN ('Analysed', 'Unavailable')");

                            t.HasCheckConstraint("ck_track_analysis_outcomes_reason", "reason IS NULL OR reason IN ('trajectory_missing', 'trajectory_integrity_failed', 'trajectory_invalid', 'trajectory_too_short')");

                            t.HasCheckConstraint("ck_track_analysis_outcomes_reference_point", "reference_point IS NULL OR reference_point IN ('bbox-centre')");

                            t.HasCheckConstraint("ck_track_analysis_outcomes_shape", "(outcome = 'Analysed' AND reason IS NULL AND reference_point IS NOT NULL) OR (outcome = 'Unavailable' AND reason IS NOT NULL AND reference_point IS NULL AND sample_count = 0 AND gap_count = 0 AND gap_total_ms = 0)");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackLineCrossing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<int>("CrossingIndex")
                        .HasColumnType("integer")
                        .HasColumnName("crossing_index");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("direction");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<long>("OffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("offset_ms");

                    b.Property<double>("PointX")
                        .HasColumnType("double precision")
                        .HasColumnName("point_x");

                    b.Property<double>("PointY")
                        .HasColumnType("double precision")
                        .HasColumnName("point_y");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("LineId", "TimestampUtc", "Direction")
                        .HasDatabaseName("ix_track_line_crossings_line_time_direction");

                    b.HasIndex("AnalysisId", "TrackId", "LineId", "CrossingIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_track_line_crossings_identity");

                    b.ToTable("track_line_crossings", null, t =>
                        {
                            t.HasCheckConstraint("ck_track_line_crossings_direction", "direction IN ('AToB', 'BToA')");

                            t.HasCheckConstraint("ck_track_line_crossings_indexes", "crossing_index >= 0 AND offset_ms >= 0");

                            t.HasCheckConstraint("ck_track_line_crossings_point", "point_x >= 0 AND point_x <= 1 AND point_y >= 0 AND point_y <= 1");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackMotionSummary", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("heading");

                    b.Property<long>("LongestStationaryMs")
                        .HasColumnType("bigint")
                        .HasColumnName("longest_stationary_ms");

                    b.Property<double>("MeanDisplacementRate")
                        .HasColumnType("double precision")
                        .HasColumnName("mean_displacement_rate");

                    b.Property<double>("PathLengthNormalised")
                        .HasColumnType("double precision")
                        .HasColumnName("path_length_normalised");

                    b.Property<string>("StationaryIntervals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stationary_intervals");

                    b.Property<string>("StationaryZoneIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stationary_zone_ids");

                    b.Property<long>("TotalStationaryMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_stationary_ms");

                    b.HasKey("AnalysisId", "TrackId");

                    b.HasIndex("LongestStationaryMs")
                        .HasDatabaseName("ix_track_motion_summaries_longest_stationary");

                    b.HasIndex("TrackId");

                    b.ToTable("track_motion_summaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_track_motion_summaries_durations", "longest_stationary_ms >= 0 AND total_stationary_ms >= 0 AND longest_stationary_ms <= total_stationary_ms");

                            t.HasCheckConstraint("ck_track_motion_summaries_heading", "heading IN ('None', 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW')");

                            t.HasCheckConstraint("ck_track_motion_summaries_json_shape", "jsonb_typeof(stationary_intervals) = 'array' AND jsonb_typeof(stationary_zone_ids) = 'array'");

                            t.HasCheckConstraint("ck_track_motion_summaries_path", "path_length_normalised >= 0 AND mean_displacement_rate >= 0");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackZoneSummary", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.Property<DateTimeOffset?>("FirstEntryTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_entry_timestamp_utc");

                    b.Property<DateTimeOffset?>("LastExitTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_exit_timestamp_utc");

                    b.Property<bool>("Loitering")
                        .HasColumnType("boolean")
                        .HasColumnName("loitering");

                    b.Property<long>("LoiteringDwellMs")
                        .HasColumnType("bigint")
                        .HasColumnName("loitering_dwell_ms");

                    b.Property<int>("LoiteringThresholdSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("loitering_threshold_seconds");

                    b.Property<long>("TotalDwellMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_dwell_ms");

                    b.Property<int>("VisitCount")
                        .HasColumnType("integer")
                        .HasColumnName("visit_count");

                    b.HasKey("AnalysisId", "TrackId", "ZoneId");

                    b.HasIndex("TrackId");

                    b.HasIndex("ZoneId", "Loitering")
                        .HasDatabaseName("ix_track_zone_summaries_zone_loitering")
                        .HasFilter("loitering");

                    b.HasIndex("ZoneId", "TotalDwellMs")
                        .HasDatabaseName("ix_track_zone_summaries_zone_dwell");

                    b.ToTable("track_zone_summaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_track_zone_summaries_counts", "visit_count >= 0 AND total_dwell_ms >= 0 AND loitering_dwell_ms >= 0");

                            t.HasCheckConstraint("ck_track_zone_summaries_loitering_threshold", "loitering_threshold_seconds > 0");

                            t.HasCheckConstraint("ck_track_zone_summaries_timestamps", "(first_entry_timestamp_utc IS NULL AND last_exit_timestamp_utc IS NULL) OR (first_entry_timestamp_utc IS NOT NULL AND last_exit_timestamp_utc IS NOT NULL AND last_exit_timestamp_utc >= first_entry_timestamp_utc)");

                            t.HasCheckConstraint("ck_track_zone_summaries_visitless", "visit_count > 0 OR (first_entry_timestamp_utc IS NULL AND total_dwell_ms = 0)");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackZoneVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<bool>("BeganInside")
                        .HasColumnType("boolean")
                        .HasColumnName("began_inside");

                    b.Property<bool>("ClosedByGap")
                        .HasColumnType("boolean")
                        .HasColumnName("closed_by_gap");

                    b.Property<long>("DwellMs")
                        .HasColumnType("bigint")
                        .HasColumnName("dwell_ms");

                    b.Property<bool>("EndedInside")
                        .HasColumnType("boolean")
                        .HasColumnName("ended_inside");

                    b.Property<string>("EntryHeading")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_heading");

                    b.Property<long>("EntryOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_offset_ms");

                    b.Property<DateTimeOffset>("EntryTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_timestamp_utc");

                    b.Property<string>("ExitHeading")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("exit_heading");

                    b.Property<long>("ExitOffsetMs")
                        .HasColumnType("bigint")
                        .HasColumnName("exit_offset_ms");

                    b.Property<DateTimeOffset>("ExitTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_timestamp_utc");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<int>("VisitIndex")
                        .HasColumnType("integer")
                        .HasColumnName("visit_index");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("AnalysisId", "TrackId")
                        .HasDatabaseName("ix_track_zone_visits_analysis_track");

                    b.HasIndex("ZoneId", "EntryTimestampUtc")
                        .HasDatabaseName("ix_track_zone_visits_zone_entry");

                    b.HasIndex("AnalysisId", "TrackId", "ZoneId", "VisitIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_track_zone_visits_identity");

                    b.ToTable("track_zone_visits", null, t =>
                        {
                            t.HasCheckConstraint("ck_track_zone_visits_dwell", "dwell_ms >= 0");

                            t.HasCheckConstraint("ck_track_zone_visits_headings", "entry_heading IN ('None', 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW') AND exit_heading IN ('None', 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW')");

                            t.HasCheckConstraint("ck_track_zone_visits_offsets", "entry_offset_ms >= 0 AND exit_offset_ms >= entry_offset_ms");

                            t.HasCheckConstraint("ck_track_zone_visits_timestamps", "exit_timestamp_utc >= entry_timestamp_utc");

                            t.HasCheckConstraint("ck_track_zone_visits_visit_index", "visit_index >= 0");
                        });
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Entity", b =>
                {
                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("RepresentativeArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Observation", b =>
                {
                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.Track", b =>
                {
                    b.HasOne("Mavi.Domain.Intelligence.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Processing.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Intelligence.Observation", null)
                        .WithMany()
                        .HasForeignKey("RepresentativeObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("TrajectoryArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Media.VideoAsset", null)
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Intelligence.VisualAttribute", b =>
                {
                    b.HasOne("Mavi.Domain.Intelligence.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Media.VideoAsset", b =>
                {
                    b.HasOne("Mavi.Domain.Cameras.Camera", null)
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Media.Artifact", null)
                        .WithMany()
                        .HasForeignKey("SourceArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Processing.ProcessingRun", b =>
                {
                    b.HasOne("Mavi.Domain.Media.VideoAsset", null)
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Processing.VisionJob", b =>
                {
                    b.HasOne("Mavi.Domain.Processing.ProcessingRun", null)
                        .WithOne()
                        .HasForeignKey("Mavi.Domain.Processing.VisionJob", "ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Scene.SceneConfiguration", b =>
                {
                    b.HasOne("Mavi.Domain.Cameras.Camera", null)
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Scene.SceneConfigurationRevision", b =>
                {
                    b.HasOne("Mavi.Domain.Media.VideoAsset", null)
                        .WithMany()
                        .HasForeignKey("ReferenceFrameVideoAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mavi.Domain.Scene.SceneConfiguration", null)
                        .WithMany()
                        .HasForeignKey("SceneConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Scene.SceneZone", b =>
                {
                    b.HasOne("Mavi.Domain.Scene.SceneConfigurationRevision", null)
                        .WithMany("Zones")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Scene.TripLine", b =>
                {
                    b.HasOne("Mavi.Domain.Scene.SceneConfigurationRevision", null)
                        .WithMany("TripLines")
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.SceneAnalysis", b =>
                {
                    b.HasOne("Mavi.Domain.Processing.ProcessingRun", null)
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Scene.SceneConfigurationRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackAnalysisOutcome", b =>
                {
                    b.HasOne("Mavi.Domain.SceneAnalytics.SceneAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackLineCrossing", b =>
                {
                    b.HasOne("Mavi.Domain.SceneAnalytics.SceneAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackMotionSummary", b =>
                {
                    b.HasOne("Mavi.Domain.SceneAnalytics.SceneAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackZoneSummary", b =>
                {
                    b.HasOne("Mavi.Domain.SceneAnalytics.SceneAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.SceneAnalytics.TrackZoneVisit", b =>
                {
                    b.HasOne("Mavi.Domain.SceneAnalytics.SceneAnalysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mavi.Domain.Intelligence.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mavi.Domain.Scene.SceneConfigurationRevision", b =>
                {
                    b.Navigation("TripLines");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
